- src/module.ts
- src/runtime/plugins/vuetify-sync.ts
This PR also splits vuetify runtime plugin into async and sync ones: `parallel: false` only required when i18n installed (we need to await i18n async plugin to be ready)
> fix: don't use file extension when registering runtime plugins

- docs/guide/date.md
- docs/guide/index.md
- package.json
- playground/locales/multiple/ar.json
- playground/locales/single/ar-EG.json
- playground/nuxt.config.mts
- playground/pages/index.vue
- pnpm-lock.yaml
- src/module.ts
- src/types.ts
- src/utils/module.ts
- src/vite/vuetify-configuration-plugin.ts
- allow load Vuetify translation messages just configuring the locales to load and configure via `vuetifyOptions.localeMessages` module option
- bump pnpm to 8.6.9
- bump vuetify to 3.3.9: v-date-picker working and date adapter also working (only tested luxon)
- allow configure date adapters
- docs: included new `vuetifyOptions.localeMessages` module option, updated types and removed warning about
> feat: allow load Vuetify translation messages

- playground/layers/vuetify-layer/nuxt.config.ts
- playground/nuxt.config.mts
- src/utils/layers.ts
- src/vite/vuetify-configuration-plugin.ts
When vuetify is missing in the Nuxt configuration file it fails or the module doesn't load the default configuration file when using layers.
This PR aso removes `labComponents` from the Vuetify virtual configuration module.
> fix: load configuration when missing vuetify module option

- docs/guide/icons/unocss-preset-icons.md
- docs/guide/index.md
- src/utils/configure-nuxt.ts
- src/utils/configure-vite.ts
Using `vite-plugin-vuetify` and removed Nuxt `components:extend` hook: if using all components, Nuxt will create common assets to be reused in pages, I'll ask what can we do with this: in the current playground there will be an `entry-**.js` with almost all Vuetify components, adding a new page with just a simple `v-btn` will reuse previous asset.
This PR also updates some broken link in Nuxt Plugin Hooks and how to configure UnoCSS Nuxt Module and the configuration to use the new Vuetify `unocss-mdi` icon set.
closes  #70
> fix: tree shaking not working

- playground/settings.scss
- src/runtime/plugins/client-hints.ts
- src/runtime/plugins/vuetify-client-hints.client.ts
- src/runtime/plugins/vuetify-client-hints.server.ts
Updated internal runtime logic and expose `ssrClientHints` directly without wrapper (keep original runtime types).
Breaking since anyone using the server  runtime `vuetify:ssr-client-hints` hook will need to update.
closes #130
> fix!: runtime SSR Client Hints types

- docs/.vitepress/pwa.ts
- docs/package.json
- netlify.toml
- pnpm-lock.yaml
- bump to `@vite-pwa/vitepress` 0.2.3 and `vite-plugin-pwa`  0.16.5
- bump to latest VP rc.24
- add hashmap.json to the sw precache manifest: https://discord.com/channels/325477692906536972/790509637598314527/1163107349851021433
- add experiamental allow list for VP integration
- remove Netlify SPA and redirections
> docs: bump to vite-pwa/vitepress v0.2.3

- src/runtime/plugins/config.ts
- src/runtime/plugins/date.ts
- src/runtime/plugins/i18n.ts
- src/runtime/plugins/vuetify-sync.ts
- src/runtime/plugins/vuetify.ts
- src/utils/icons.ts
This is a DX improvement when developing - we can avoid loading the entire barrel file at `#app` by using the new granular imports merged in https://github.com/nuxt/nuxt/pull/23951.
> fix: import nuxt composables from #imports

- src/module.ts
- src/utils/config.ts
- src/vite/vuetify-configuration-plugin.ts
- src/vite/vuetify-date-configuration-plugin.ts
- some/all labs components moved to components
- date options: now there is no need vuetify date adapter to import it (https://github.com/vuetifyjs/vuetify/issues/18593)
`Luxon` date adapter stops working: https://github.com/vuetifyjs/vuetify/issues/18642
closes #147
> feat: add support for Vuetify 3.4

- docs/guide/vuetify-composables.md
- playground/pages/index.vue
- src/utils/configure-nuxt.ts
`useDate` excluded from Nuxt auto-import:
- Vuetify 3.4+ import from `vuetify`
- Vuetify < 3.4 import from `vuetify/labs/date`: missing import (added in this PR)
> fix: add missing auto-import for `useDate` composable for vuetify < 3.4

- date-io-playground/nuxt.config.ts
- date-io-playground/package.json
- docs/guide/index.md
- docs/guide/server-side-rendering.md
- package.json
- playground/nuxt.config.ts
- playground/package.json
- pnpm-lock.yaml
- src/types.ts
- src/utils/configure-vite.ts
- src/vite/vuetify-import-plugin.ts
- src/vite/vuetify-styles-plugin.ts
There is no way, `vite-plugin-vuetify` didn't fix SSR problem, this PR just updates the new types for `@vuetify/loader-shared`: enabling custom SASS variables with same error and not working.
This PR also updates Vuetify to `v3.4.8`.
closes #173
> feat!: Vite 5, Nuxt 3.9.0 and Vuetify Vite Plugin 2.0.1

- docs/.vitepress/config.ts
- docs/guide/i18n.md
- docs/guide/icons/integrations.md
- package.json
This PR also updates the i18n section: required `@nuxtjs/i18n v8.0.0+`
closes #181
> docs: add custom icon integrations section

- docs/guide/icons/integrations.md
This PR also updates all integration links to the corresponding GH repos: created icnofy for vue and phosphor vue repositories
> docs: include iconify icon web component integration

- playground/middleware/1.vuetify.global.ts
- playground/middleware/vuetify.ts
- playground/pages/index.vue
- src/runtime/plugins/vuetify-sync.ts
- src/runtime/plugins/vuetify.ts
This PR will configure Vuetify plugin without `app:create` Nuxt  hook: will allow to use `useNuxtApp().$vuetify` also in middlewares.
I'm going to request (and maybe implement) a new Nuxt feature to allow use any nuxt vuetify runtime plugin in parallel: https://github.com/nuxt/nuxt/issues/25141
releated #179 This PR will not resolve the issue since it is a problem releated to storybook, tested on my local with local tgz from this PR and still missing styles and icons
closes #87
> feat!: change main vuetify plugins logic

- src/module.ts
- src/utils/configure-nuxt.ts
- src/utils/vuetify-nuxt-plugins.ts
- src/utils/vuetify-plugin-template.ts
This PR splits Vuetify Nuxt plugin template in client and server plugin templates, moving `dependsOn` inside the `getContents` callback.
> fix: vuetify nuxt plugins templates must be statically analysable

- playground/assets/custom-vuetify.scss
- playground/assets/settings.scss
- playground/nuxt.config.ts
- src/vite/vuetify-styles-plugin.ts
- test/basic.test.ts
- test/fixtures/basic/app.vue
- test/fixtures/sass/app.vue
- test/fixtures/sass/nuxt.config.ts
- test/fixtures/sass/package.json
- test/fixtures/sass/vuetify-settings.scss
- test/sass.test.ts
Fixing the tests plugin error
Changes made in this pull request:
- Creating test to detect error
- Fixing error by adding `plugin-vuetify/lib` checker
Fixed error:
```
FAIL  test/sass.test.ts > sass
Error: Could not load /plugin-vuetify/lib/components/VApp/VApp.sass?inline&used: ENOENT: no such file or directory, open '/plugin-vuetify/lib/components/VApp/VApp.sass?inline&used'
```
All tests passed now:
```
✓ test/detect-browser.test.ts (10)
✓ test/basic.test.ts (1) 10065ms
✓ test/sass.test.ts (1) 12979ms
Test Files  3 passed (3)
Tests  12 passed (12)
Start at  14:32:47
Duration  13.72s (transform 88ms, setup 0ms, collect 740ms, tests 23.05s, environment 1ms, prepare 292ms)
```
closes #191
> Fixing the tests plugin error

- src/utils/configure-nuxt.ts
- src/vite/constants.ts
This PR will transpile:
- vuetify
- vuetify nuxt module runtime folder
- vuetify nuxt plugins (client and server)
- all vuetify vite virtual configuration modules: check [nuxt:imports-transform](https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/imports/transform.ts)
When importing stuff from `#imports`  from vuetify virtual condiguration modules Nuxt not transforming the import and so will break the application:
```shell
[nuxt] `#imports` should be transformed with real imports. There seems to be something wrong with the imports plugin.
```
closes #200
> fix!: transpile vuetify, runtime dir, vuetify plugin and virtual modules

- playground/pages/index.vue
- playground/plugins/vuetify.ts
- src/module.ts
- src/utils/vuetify-nuxt-plugins.ts
This is a very early PR to make this module compatible with [changes we expect to release in Nuxt v5](https://github.com/nuxt/nuxt/issues/25323).
In [Nuxt v3.7.0](https://github.com/nuxt/nuxt/releases/tag/v3.7.0) we added support for `import.meta.*` (see [original PR](https://github.com/nuxt/nuxt/pull/22428)) and we've been gradually updating docs and moving across from the old `process.*` patterned variables.
As I'm sure you're aware, these variables are replaced at build-time and enable tree-shaking in bundled code.
This change affects _runtime_ code (that is, that is processed by the Nuxt bundler, like vite or webpack) rather than code running in Node. So it really doesn't matter what the string is, but it makes more sense in an ESM-world to use `import.meta` rather than `process`.
(It …
> fix!: opt in to `import.meta.*` properties

- src/utils/loader.ts
We are planning to move to [emitting absolute paths in `builder:watch` in Nuxt v4](https://github.com/nuxt/nuxt/issues/25339). You can see a little more about the history in the PR linked in that issue.
This PR is an attempt to use a forward/backward compatible approach, namely resolving the path to ensure it's absolute, then making it relative so your existing code will continue to work.
This should be safe to merge as is, but do let me know if you have any concerns about this approach.
> fix: adopt forward-compatible approach to `builder:watch`

- date-io-playground/nuxt.config.ts
- date-io-playground/package.json
- docs/.vitepress/config.ts
- docs/guide/faq.md
- docs/guide/vuetify-composables.md
- docs/package.json
- package.json
- playground/nuxt.config.ts
- playground/package.json
- playground/plugins/vuetify.ts
- pnpm-lock.yaml
- src/module.ts
- src/types.ts
- src/utils/config.ts
- src/utils/configure-nuxt.ts
- include new `useGoTo` composable (detecting 3.5+)
- bump Nuxt to 3.11.1 (playgrounds and internal dependencies)
- docs: include changes in Polaris
- docs: include FAQ section
> feat: include Vuetify Polaris changes (3.5.0)

- README.md
- docs/guide/i18n.md
Updates the links to point to the latest docs, we should probably redirect the previous URL to the latest docs as well.
> docs: update link to Nuxt i18n docs

- README.md
- docs/guide/index.md
This updates the documentation to use the [`nuxi module add` command](https://github.com/nuxt/cli/pull/197) which should simplify docs a bit and also improve user experience as there's no need to add to `nuxt.config` manually.
It's documented [here](https://nuxt.com/docs/api/commands/module#nuxi-module-add).
I may have missed a few spots in the documentation as I'm doing this across the modules ecosystem assisted by the power of regular expressions ✨, so I'd appreciate a review 🙏
> docs: use new `nuxi module add` command in installation

- playground/pages/index.vue
- src/utils/configure-nuxt.ts
During my troubleshooting #212, regarding using custom Sass styles in components, only by manually importing Vuetify styles the custom Sass changes are applied without causing UI disruption.
```js
vuetify: {
moduleOptions: {
styles: {
configFile: 'assets/scss/settings.scss',
},
},
},
css: [
'vuetify/styles',
],
```
With this tiny fix,  styles will always be imported therefore no manual syle import is necessary anymore.
This is a suggestion from Kael.
> fix: should always include styles

- src/utils/layers.ts
- load configuration in reverse order: layers first
- dedupe icons sets
closes #217 
closes #218
Issue 217 reproduction with this PR:
Issue 218 reproduction with this PR:
> fix: load configuration correctly

- src/utils/configure-nuxt.ts
- src/utils/configure-vite.ts
It seems latest nuxt (maybe can be also vue 3.4) including `vite.vue.template.transformAssetUrls`, this PR just merges existing, vuetify and user provided
https://github.com/nuxt/nuxt/blob/7c8f78d27e54f1adc1527e38b232ad9852058fe1/packages/schema/src/config/app.ts#L11-L18
closes #220
> fix: `transformAssetUrls` stops working

- src/vite/vuetify-configuration-plugin.ts
This PR just writes the configuration without using JSON.parse, some locales using some chars breaking json. This may have some (small) performance loss.
closes #222
> fix: don't use JSON parse to load configuration

- date-io-playground/nuxt.config.ts
- date-io-playground/package.json
- docs/guide/index.md
- docs/guide/server-side-rendering.md
- modern-sass-compiler/assets/main.scss
- modern-sass-compiler/assets/settings.scss
- modern-sass-compiler/nuxt.config.ts
- modern-sass-compiler/package.json
- package.json
- playground/assets/main.scss
- playground/assets/settings.scss
- playground/nuxt.config.ts
- playground/package.json
- playground/pages/index.vue
- pnpm-lock.yaml
- src/module.ts
- src/types.ts
- src/utils/config.ts
- src/utils/configure-nuxt.ts
- src/utils/configure-vite.ts
- src/vite/vuetify-import-plugin.ts
- src/vite/vuetify-styles-plugin.ts
- vuetify-locale-playground/nuxt.config.ts
- vuetify-locale-playground/package.json
- fix missing sass source files warnings  when using SASS variables (only for virtual sass files)
- fix vue router warnings when using SASS variables (only for virtual sass files)
- update sass configuration logic checking Vite version
- disable `features.inlineStyles` or `experimental.inlineSSRStyles` when SSR is enabled
- include new option to disable registering `vuetify/styles` for advance SASS files usages
- docs: update module options
Once https://github.com/vuetifyjs/vuetify-loader/pull/338 merged and released we can use the Vuetify Vite plugin here.
---
> [!TIP]
> feat!: update auto import and styles Vite plugins

- package.json
- pnpm-lock.yaml
This PR fixes an internal breaking change at Vuetify version 3.7.11, import maps and import labs maps have changed, this PR updates the plugin (import maps used by the plugin that has been updated, but the module not updated). 
---
> [!TIP]
> fix: update vuetify vite plugin to 2.1.0

- docs/guide/faq.md
- docs/guide/globals/index.md
- docs/guide/globals/lab-components.md
- src/utils/configure-vite.ts
Right now there is no way to use component labs if not registering them globally, this PR enables component labs auto-import by default.
---
> [!TIP]
> feat(labs): enable labs components auto-import by default

- src/module.ts
Since nuxi v3.8, we've supported setting `nuxt.options.nitro.static` instead of `nuxt.options._generate` (which is an internal flag) - see https://github.com/nuxt/nuxt/pull/21860.
Now, in preparation for Nuxt v4, we've removed the types for `_generate` (see https://github.com/nuxt/nuxt/pull/32355). This PR adds support for new version in backwards compatible way (ignoring type issues) - I'd suggest you remove support in a future major.
---
> [!TIP]
> fix: update `isNuxtGenerate` flag to use `nitro.static`
