src/module.ts
src/styles-plugin.ts

fix: replace upath with pathe

---

src/module.ts

Using `vuetify/dist/json/importMap.json` file to register Vuetify components in Nuxt `.nuxt/components.d.ts`.
closes #15

feat: load Vuetify components using Nuxt

---

README.md
playground/nuxt.config.mts
src/module.ts
src/runtime/plugins/i18n.ts
src/types.ts
src/utils/icons.ts
src/vite/vuetify-configuration-plugin.ts

closes #18
closes #27 
closes #28

feat!: add global components, aliases and blueprint support

---

src/vite/vuetify-configuration-plugin.ts

fix: directives included when configuring `false`

---

playground/nuxt.config.mts
src/module.ts
src/vite/vuetify-configuration-plugin.ts

fix: use importMap.json and importMap-labs.json to create imports

---

src/module.ts

fix: vuetify components resolved to any type

---

playground/nuxt.config.mts
src/utils/icons.ts

fix: custom cdn icon font ignored

---

playground/nuxt.config.mts
playground/pages/index.vue
src/runtime/plugins/i18n.ts
src/types.ts
src/utils/layers.ts

fix: i18n integration not working

---

package.json
pnpm-lock.yaml

fix(deps): remove peer dependencies

---

docs/guide/index.md
src/types.ts

Add mention about disabling inlineSSRStyles when configFile and SSR. Link to the issue.

feat: add inlineSSRStyles hint to types

---

docs/.vitepress/theme/VuetifyLayout.vue
docs/.vitepress/theme/index.ts
docs/.vitepress/theme/styles/main.css
docs/.vitepress/theme/styles/vars.css
docs/package.json
pnpm-lock.yaml

This PR also includes the radial theme switcher transition

docs: bump to VitePress v1.0.0-rc11

---

docs/.vitepress/sitemap.ts
playground/plugins/custom-unocsss-mdi.ts
playground/vuetify.config.mts
src/runtime/plugins/icons.ts
src/types.ts
src/utils/config.ts
src/utils/icons.ts
src/vite/vuetify-icons-configuration-plugin.ts
src/vite/vuetify-styles-plugin.ts

fix: update icon aliases logic

---

src/utils/icons.ts

fix: icons stop working

---

src/runtime/plugins/vuetify-client-hints.client.ts
src/runtime/plugins/vuetify-client-hints.server.ts

fix: add missing imports in client hints plugins

---

docs/guide/nuxt-plugin-hooks.md
playground/plugins/vuetify.ts
src/runtime/plugins/config.ts
src/types.ts

I created a PR for #111  feat request.

feat: add vuetify:ready hook

---

docs/guide/index.md
docs/guide/server-side-rendering.md

docs: update module options and ssr entries

---

playground/vuetify.config.mts
src/vite/vuetify-configuration-plugin.ts

fix: wrong import directives

---

playground/nuxt.config.mts
src/utils/configure-nuxt.ts
src/utils/configure-vite.ts

closes #88 
closes #123
/cc @TechAkayy

fix: handle SSR configuration properly

---

docs/guide/index.md
package.json
playground/nuxt.config.mts
playground/pages/index.vue
src/types.ts
src/utils/configure-nuxt.ts
src/utils/index.ts

@TechAkayy just tested with v-card
closes #125

feat: allow extends Vuetify transformAssetUrls

---

src/runtime/plugins/vuetify-client-hints.server.ts

fix: use h3 to handle http headers

---

package.json
playground/layer-module/nuxt.config.ts
playground/package.json
pnpm-lock.yaml
src/runtime/plugins/vuetify-client-hints.client.ts
src/runtime/plugins/vuetify-client-hints.server.ts
src/runtime/plugins/vuetify-no-client-hints.ts
src/runtime/plugins/vuetify-sync.ts
src/runtime/plugins/vuetify.ts
src/types.ts
src/utils/configure-nuxt.ts

fix: module augmentation types

---

src/utils/configure-nuxt.ts

feat: auto-import the new `useDate` composable

---

custom-configuration.d.ts
package.json
scripts/postbuild.ts

fix: package types

---

docs/guide/nuxt-layers-and-module-hooks.md

You don't need to declare the module in the main project, only in the base layer

docs: clarify how to install in a layer

---

docs/guide/icons/font-icons.md
playground/vuetify.config.ts

docs: update mdi cdn url in font icons page

---

package.json
playground/package.json
pnpm-lock.yaml

feat!: update vuetify to 3.6.5

---

package.json
playground/vuetify.config.ts
src/vite/vuetify-configuration-plugin.ts

fix: dedupe imports

---

package.json
src/utils/layers.ts

fix(layers)!: root layer should be the last one when merging

---

date-io-playground/package.json
package.json
playground/package.json
pnpm-lock.yaml
pnpm-workspace.yaml
src/module.ts
src/utils/configure-vite.ts
src/utils/index.ts
vuetify-locale-playground/package.json

feat!: add Nuxt 3.12 support

---

docs/.vitepress/config.ts
docs/guide/transform-asset-urls.md
src/module.ts
src/types.ts

fix: initialize transform asset urls correctly

---

src/runtime/plugins/vuetify-client-hints.server.ts

This PR removes drawer animation in desktop browsers: DPR header sent to the client (`Accept-CH`), and chromium browsers sending DPR header with 1.25.

fix: omit DPR header on desktop browsers

---

.github/workflows/publish-commit.yml

chore: add `pkg.pr.new`

---

package.json

chore: update `pnpm` to 9.9.0

---

src/module.ts

There is no need to add Nuxt module augmentations.
---
> [!TIP]

fix: remove Nuxt module augmentations

---

docs/guide/faq.md

docs: add Vuetify styles broken fix when using Nuxt 3.16 to the FAQ page

---

src/vite/vuetify-styles-plugin.ts

This PR uses `fsp.access` instead `fs.existsSync` and re-throws legitimate errors when checking Vuetify SASS components files.
---
> [!TIP]

perf(styles): use `fsp.access` and rethrow legitimate errors

---

package.json

chore: update pnpm to `v10.10.0`
